- name: infoscience-exports Config Maps
  openshift:
    state: latest
    resource: ConfigMaps
    name: "{{ config_maps_name }}"
    content: |
      apiVersion: v1
      data:
        DJANGO_SETTINGS_MODULE: 'settings.prod'
        SITE_URL: 'https://infoscience-exports.epfl.ch'
        SITE_PATH: '/'
        DEV_PORT: '3000'
        ALLOWED_HOSTS: 'infoscience-exports.epfl.ch,infoscience.epfl.ch'
        CACHE_TIMEOUT: '7200'
        RANGE_DISPLAY: '100'
      kind: ConfigMap
      metadata:
        name: "{{ config_maps_name }}"
        namespace: "{{ openshift_namespace }}"
