- name: infoscience-exports route
  openshift:
    state: latest
    resource: Route
    name: "{{ route_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ route_name }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          app: "{{ app_name }}"
          author: jdelasoie
          team: idev-fsd
        annotations:
          authors: idev-fsd
      spec:
        host: "{{ cname }}"
        port:
          targetPort: "80"
        tls:
          termination: edge
        to:
          kind: Service
          name: "{{ svc_name }}"
          weight: 100
        wildcardPolicy: None
