- name: infoscience-exports secrets
  openshift:
    state: latest
    resource: Secret
    name: "{{ secret_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: v1
      stringData:
        mongo-url: 'mongodb://{{ db_user }}:{{ db_password }}@{{ db_host }}.epfl.ch/{{ db_name }}'
        meteor-settings: '{{ lookup("env", "METEOR_SETTINGS") }}' # MOVE this to KEYBASE
      kind: Secret
      metadata:
        name: "{{ secret_name }}"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
