- name: infoscience-exports service
  openshift:
    state: latest
    resource: Service
    name: "{{ svc_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ svc_name }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          app: "{{ app_name }}"
          author: jdelasoie
          team: idev-fsd
        annotations:
          authors: idev-fsd
      spec:
        ports:
        - name: "443"
          port: 443
          protocol: TCP
          targetPort: 3000
        selector:
          app: "{{ app_name }}"
          deployment: "{{ deploy_name }}"
        type: ClusterIP
